version: '3.4'
services:
    app:
        image: oyurimatheus/whowantsabeer
        container_name: app
        ports:
          - 5000:5000
        depends_on:
          - db
        restart: on-failure
        environment:
          - DATABASE_NAME=whowantsabeer
          - DATABASE_USER=app
          - DATABASE_PASSWORD=app
          - DATABASE_HOST=172.16.1.2
          - DEBUG=False
        networks: 
            beer:
                ipv4_address: 172.16.1.3
    db:
        image: mdillon/postgis
        environment:
          - POSTGRES_PASSWORD=app
          - POSTGRES_USER=app
          - POSTGRES_DB=whowantsabeer
        ports: 
          - 5432:5432
        networks: 
            beer:
                ipv4_address: 172.16.1.2

networks:
    beer:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.1.0/24
                