version: '3.4'
services:
    app:
        image: oyurimatheus/whowantsabeer
        container_name: app
        ports:
          - 5000:5000
        depends_on:
          - db
        restart: on-failure
        environment:
          - DATABASE_NAME=whowantsabeer
          - DATABASE_USER=app
          - DATABASE_PASSWORD=app
          - DATABASE_HOST=db
          - DEBUG=False
    db:
        image: mdillon/postgis
        environment:
          - POSTGRES_PASSWORD=app
          - POSTGRES_USER=app
          - POSTGRES_DB=whowantsabeer